version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker pull adoptopenjdk/openjdk11:alpine-jre
      - docker tag adoptopenjdk/openjdk11:alpine-jre $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/openjdk11:alpine-jre

  build:
    commands:
      - echo Building the Docker image...
      - mvn compile com.google.cloud.tools:jib-maven-plugin:3.1.1:dockerBuild
      - docker tag $IMAGE_REPO_NAME:1 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
  post_build:
    commands:
      - echo Build completed
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
#cache:
#  paths:
#    - '/root/.m2/**/*'